Default.txt

When connecting with Tunnelblick client I received following error:
```
TLS_ERROR: BIO read tls_read_plaintext error: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
TLS Error: TLS object -> incoming plaintext read error
TLS Error: TLS handshake failed
```
To fix the problem the same **tls-version-min** directive used in server configuration has to be added to the client config.

Fix TLS handshake error

---

scripts/makeOVPN.sh

Fixes: #28 #62 #85 #99. This was caused by `expect` timing out if the key generation took too long.

fixes expect timeout

---

auto_install/install.sh

Added option to download Diffie-Hellman parameters from 2ton.com.au if keysize >= 4096.

Added option to download DH parameters

---

auto_install/install.sh

Fetch random DH params from the last 128 generated by 2ton.com.au. This will reduce the likelihood that multiple installs in short period of time will share the same DH params.

Randomize DH params fetched from 2ton.com.au

---

auto_install/install.sh

New text:
> Download Diffie-Hellman parameters from a public DH parameter generation service?
> 
> Generating DH parameters for a $ENCRYPT-bit key can take many hours on a Raspberry Pi. You can instead download DH parameters from "2 Ton Digital" that are generated at regular intervals as part of a public service. Downloaded DH parameters will be randomly selected from a pool of the last 128 generated.
> More information about this service can be found here: https://2ton.com.au/dhtool/
>
> If you're paranoid, choose 'No' and Diffie-Hellman parameters will be generated on your device.
- Change default from "no" to "yes," since it's perfectly safe for 99% of users **(Reverted to "no" being default)**
- Be a bit more specific about what "a long time" means
- Provide a bit of information about …

Explain DH param download in greater detail

---

README.md
auto_install/install.sh
pivpn
scripts/makeOVPN.sh
scripts/removeOVPN.sh

I ported the functionality from the pi-hole script to fix #223 (#86). I finished implementing it but more people should try it before merging.
- Parameters will be stored in `/etc/pivpn/setupVars.conf`
- added a finalExports function
- added an update_dialogs function to ask what to do if a parameter file was found
- added an updatePiVPN function
Moved some stuff around.
This request is ready for testing.

Implemented "--unattended" option (Issue #223)

---

auto_install/install.sh

During the installation procedure, a user is presented multiple times with a list of items to choose from. These are selected by pressing the space bar. However, this is only indicated textually at the step where the user selects which interface to use. This pull request adds this text to every item selection step. Presumably fixes issue #232 .

Clearly and consistently indicate that a user selects a list item with the space bar.

---

auto_install/install.sh

I just downloaded and installed Devuan (1.0) on my PI3. I wanted to test out pivpn on it and with these mods, it will install and work.
Just thought I'd pass it on as a pull request.
Thanks.
Changes:
- To simplify further additions to PLAT or OSCN, use
the case command for checking
- Treat Devuan as Debian
- Add /sbin:/usr/sbin to PATH before calling ifconfig
- Ensure net-tools is installed so we have ifconfig

Support for Devuan

---

README.md

A extremely trivial issue. Markdown doesn't consider them links because of the space.

Fixed links in README.md on lines 156 and 158

---

auto_install/install.sh
scripts/removeOVPN.sh
server_config.txt

Implemented that an empty certificate revocation list is generated during installation after generation of other parts of the Public Key Infrastructure. The added benefit of this is that whenever the user now revokes a client, the change is instant. Whereas before, the first time a revocation happened since the installation of PiVPN, the OpenVPN server had to be restarted to enable the then-newly-generated CRL (causing an interruption of service for other connected clients). This change also makes the file /etc/pivpn/REVOKE_STATUS obsolete.
Documentation: https://openvpn.net/index.php/open-source/documentation/howto.html#revoke

Generate and activate CRL during installation

---

auto_install/install.sh
server_config.txt

The SERVER_NAME variable is used in a `verify-x509-name` check to allow the client to verify it is talking to the correct server (based on the server certificate Common Name). However, the variable's value was always equal to `server`. This wasn't unique for each installation and therefore provided no additional safety. So I've modified it to be random for each installation of PiVPN.
Additionally, the client config contains the `remote-cert-tls` option to check for appropriate key usage, but the server config didn't so I added it.
Source for obtaining a random UUID (thank you): Earthgecko (https://gist.github.com/earthgecko/3089509)

Randomize server Common Name for added security

---

auto_install/install.sh
server_config.txt

Reordered and cleaned up the list items. Added a warning for using 1024-bit encryption. Changed the placeholder DH param filename in server_config.txt from 1024 bit to 2048 bit to set the right example (purely cosmetic, the value is replaced by the installation script).

Improved encryption strength selection menu

---

scripts/clientStat.sh

pivpn clients script was showing clients in only one line, and titles were not properly aligned. 
Fixed confits due to my local repo not syncing correctly, tested, everything is fine now!

Fix Clients only in one line

---

scripts/makeOVPN.sh

As @fyellin in the comments, there is some chatter on other groups that some OpenVPN implementations cannot handle client keys that are encrypted with RSA.
If the client key is encrypted, we might re-encrypting the current client key using 3DES.
This commit will convert user client key to 3DES in command `pivpn -a`
P/S: All credits to @fyellin. Many thanks to him.

Issue-171: Error using iOS OpenVPN

---

Default.txt
auto_install/install.sh
scripts/makeOVPN.sh
server_config.txt

This pull request contains an option for the user to add openvpn 2.4 features:
- tls-crypt instead of tls-auth to encrypt (not only authenticate) the control channel
- elliptic curves for the key exchange (no need to generate/download dh parameters)
- compress lz4 instead of compl-lzo for less cpu intensive compression
I also changed the logging behavior: current implementation only keeps the log until daemon restart, now openvpn uses rsyslog so we can easily enable log rotation (see confLogging function). 
P.S Sorry for the other wrong pull request

2.4 Updates

---

auto_install/install.sh
server_config.txt

Added support for FamilyShield DNS from OpenDNS/CISCO. 
With a very minor code change, individuals can now implement restrictions on dangers, disturbing, or otherwise adult oriented content without the need for managed restrictions. 
This is a fairly non-invasive change and will benefit users who intend to use VPN for home or small business uses where access to such material may be undesirable.

Updated install.sh

---

server_config.txt

Added fix to prevent DNS leak on Windows systems. If the OS on the client side is Linux, this option is ignored by the client.

DNS leak fix in server_config.txt

---

auto_install/install.sh
scripts/makeOVPN.sh

- Simplified [distro_check](https://github.com/orazioedoardo/pivpn/blob/master/auto_install/install.sh#L82) function.
- New [addSoftwareRepo](https://github.com/orazioedoardo/pivpn/blob/master/auto_install/install.sh#L407) function to add the openvpn repo. Actually [checkForDependencies](https://github.com/orazioedoardo/pivpn/blob/master/auto_install/install.sh#L505) was supposed to do this but it is [commented out](https://github.com/orazioedoardo/pivpn/blob/master/auto_install/install.sh#L1284), looks like it had been spit into individual functions later.
- Simplified [DNS server](https://github.com/orazioedoardo/pivpn/blob/master/auto_install/install.sh#L709) choise.
- Do not prompt to enable 2.4 features if Raspbian [is not](https://github.com/orazioedoardo/pivpn/blob/master/auto_insta …

Several changes and some fixes

---

auto_install/install.sh

When runUnattended is set to true /etc/pivpn/TWO_POINT_FOUR file is not created because useUpdateVars is set to true and it skips the validation in line 837.

Create TWO_POINT_FOUR file when running unattended

---

scripts/makeOVPN.sh

Prevent 'send' from interpreting passwords beginning with '-' as options.

---

Default.txt

As issue #589 points out, this option is necessary to prevent a warning about caching passwords in memory.

Add auth-nocache option to client.

---

scripts/makeOVPN.sh
scripts/pivpnDebug.sh
scripts/removeOVPN.sh

right adjustment
- read for "other" withdrawn from .ovpn files
- delete also /etc/openvpn/easy-rsa/pki/${CERTS_TO_REVOKE[ii]}.ovpn after remove certificate
Telekom Hybrid Check 
- Small check whether Telekom Hybrid will be used to give helpful tips.

Some enhanced (rights & telekom hybrid)

---

auto_install/install.sh

Update easy-rsa version to v3.0.6, which would allow for us to implement a certificate renewal option, since easy-rsa now supports certificate renewal (https://github.com/OpenVPN/easy-rsa/pull/286)!

Update easy-rsa version

---

auto_install/install.sh

This pull request fixed rsyslog deprecation warning found in `/var/log/syslog`.
In one of my machine, `sudo service rsyslog restart` failed to create `/var/log/openvpn.log`.
However, this was fixed upon incorporating the change made in this pull request.
https://www.rsyslog.com/doc/v8-stable/compatibility/v7compatibility.html#omruleset-and-discard-action-are-deprecated
According to the link above:
> omruleset and discard (~) action are deprecated
>
> Both continue to work, but have been replaced by better alternatives.
>
> The discard action (tilde character) has been replaced by the “stop” RainerScript directive. It is considered more intuitive and offers slightly better performance.
> 
> The omruleset module has been replaced by the “call” RainerScript directive. Call permits to execute …

Fixed rsyslog deprecated discard from ~ to stop

---

auto_install/install.sh
scripts/makeOVPN.sh

As per request on issue #530 I added the ability to make client certificates last a custom number of days. 
I also relaxed the check for characters in the username as suggested in #696.
@Giraffe1966 pointed out that clients starting with dot would be hidden, so I chose just not to allow them.
Similarly, names starting with dash should also not be allowed since they would be interpreted as command line arguments when provided via... command line argument.

Custom certificate duration and more flexible names

---

scripts/clientStat.sh

Running [shellcheck](https://github.com/koalaman/shellcheck):
```
shellcheck clientStat.sh
In clientStat.sh line 23:
if [ -n $(type -t numfmt) ]; then
^---------------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].
```
This PR fixes the issue [SC2070](https://github.com/koalaman/shellcheck/wiki/SC2070)

ensure -n checks returned value

---

auto_install/install.sh
scripts/pivpnDebug.sh
scripts/uninstall.sh

Handle non-default firewall configuration where the user may already have some rules that drop incoming packets or block forwarding, like this one #774.
Also: removed `$SUDO` from the uninstall script since `pivpn` already calls it with sudo.

Improve iptables detection

---

auto_install/install.sh
scripts/pivpnDebug.sh

This pull requests redacts all public IP addresses inside the snippet of the server log, which are usually client IPs. It does such by using grepcidr to select lines with non private IP ranges, uses grep and uniq to extract the individual IPs and sed to replace them.

Hide client IPs inside the debug log

---

auto_install/install.sh

Just noticed this, otherwhise the script will exit on other platforms because of `set -e`.

Only use iptables-legacy if platform is Buster

---

auto_install/install.sh
scripts/makeOVPN.sh

- Issue a server cert that lasts 3650 days instead of the default 1080, so it won't expire before client certs that last more than 1080 days: https://github.com/pivpn/pivpn/issues/784#issuecomment-508844437
- Actually allow dashes in usernames (@mquirin): https://github.com/pivpn/pivpn/issues/786
- The script called `update_repo` [without the second argument](https://github.com/pivpn/pivpn/blob/8e3a95152412a9d35b67d51bfc80379350815252/auto_install/install.sh#L531), the pivpn git url, making `git clone [...]` fail. Moreover, since `/etc/.pivpn`, the current working directory, is deleted [here](https://github.com/pivpn/pivpn/blob/8e3a95152412a9d35b67d51bfc80379350815252/auto_install/install.sh#L547), git will complain, so we move back to /etc: https://github.com/pivpn/pivpn/issues/787
``` …
```

Miscellaneous fixes

---

auto_install/install.sh
scripts/pivpnDebug.sh
scripts/uninstall.sh

Change UFW forward  policy to accept instead of adding a rule with 'route' if tha package version is older that 0.34. Should fix https://github.com/pivpn/pivpn/issues/799.

Handle older UFW version from Jessie

---

scripts/makeOVPN.sh

Fix https://github.com/pivpn/pivpn/issues/798. Also changed "tls-auth" text to "tls" to avoid confusion when "tls-crypt" is used.

Recreate ovpn folder if deleted

---

auto_install/install.sh
pivpn
scripts/makeOVPN.sh
scripts/pivpnDebug.sh
scripts/uninstall.sh

First time contributing to an open source project, so apologies if I'm breaking some unspoken rules. I'm a big fan of this project and hope that this might be useful to some people.
I wanted to set up PiVPN by using my password manager Bitwarden and decided to add it into the installation script. I tested this on my Pi which runs Raspbian Buster and used the updated code from the pivpn test branch to test the Buster support.
**Notes:**
- For some reason the installation script didn't like npm and nodejs as part of the packages, so I had to make a separate function for that. I imagine there's probably a less messy way to integrate it.
- When creating the object in the vault, I could not figure out how to hide the output and was unfortunately unable to find it in the Bitwarden CLI …

integrated bitwarden password manager into pivpn

---

auto_install/install.sh

Historic versions leveraged a format of "server_$UUID" to name of the VPN server certificate for X509 verification.  This seems very impersonal.  The new code pulls the existing hostname of the machines and appends the 16 character UUID.  The new format is $hostname_$UUID.
Example:
A machine named "Martian" with a UUID of 1234567890123456 would change from server_1234567890123456 to Martian_1234567890123456

Leverage the Hostname of the Server

---

scripts/makeOVPN.sh
scripts/removeOVPN.sh

Added new step to create an .ovpn12 file that can be stored on iOS keychain
This step is more secure method and does not require the end-user to keep entering passwords, or storing the client private cert where it can be easily tampered based on documentation located:
https://openvpn.net/faq/how-do-i-use-a-client-certificate-and-private-key-from-the-ios-keychain/
Someone can improve upon this by adding a parameter (possibly -i|--iOS) and then generating the original .ovpn file to not contain the client private certificate.

.ovpn12 files

---

auto_install/install.sh
scripts/makeOVPN.sh
scripts/removeOVPN.sh
scripts/uninstall.sh

Reference: https://github.com/pivpn/pivpn/pull/809#issuecomment-526927268
+ When estimating `$INSTALL_HOME`, assure grep can only match user names, to avoid possible wrong multi-line value
+ Remove possible trailing slash from `$INSTALL_HOME`, to avoid double slash in "`$INSTALL_HOME/ovpns`"
+ Avoid "`cat <file> | grep <pattern>`", since grep can process files directly
+ Avoid "`VAR=$(cat file)`", since "`VAR=$(<file)`" has the same result without using a slow external command
Signed-off-by: MichaIng <micha@dietpi.com>

Failsafe home dir obtaining

---

pivpn
scripts/makeOVPN.sh

`-passin env:$PASSWD` reads the password from the `$PASSWD` environment variable, but `$PASSWD` is not an environment variable, it's the actual password. Now using `-passin pass:"$PASSWD"` to fix.
`--bitwarden` option is shown both when running `pivpn` and running `pivpn -a` which seems redundant to me, so I removed it from `pivpn`. However, to make it discoverable, together with `--iOS` and `--days`, we show the client creation options the first time the user runs `pivpn -a`.

Fix .ovpn12 file, make pivpn -a options discoverable

---

auto_install/install.sh

Addresses #829 , can specify subdomains. 
Regex specifies : must start with alphanumeric, may have no more
than two consecutive hyphens, must not end or start with hyphen,
final word must be at least two apha characters.
Signed-off-by: Rob Gill <rrobgill@protonmail.com>

Allow subdomains in custom dns search list

---

auto_install/install.sh

MakeOVPN has been updated to include the -i iOS function to allow users to create an OVPN12 format file that can be used with the iOS keychain.  Since the OVPN12 format is incompatible with OpenVPN 2.4 - this change creates a configuration file that determines if the user can create a -i request via MakeOVPN.

Create OVPN12_Compatible file

---

scripts/makeOVPN.sh

the -i iOS function is not compatible with OVPN 2.4.  This change checks to ensure that the user is not using this version before attempting to create an OVPN12 file.

Check if -i iOS can be used

---

auto_install/install.sh
scripts/openvpn/backup.sh
scripts/openvpn/makeOVPN.sh
scripts/openvpn/pivpn
scripts/openvpn/removeOVPN.sh
scripts/openvpn/update.sh
scripts/uninstall.sh
scripts/wireguard/qrcodeCONF.sh
scripts/wireguard/removeCONF.sh

This pull requests brings back the uninstall script, which means that `pivpn -u` works again. The uninstall script will only prompt to uninstall packages that where not already installed at the time of the PiVPN installation. `installDependentPackages()` will add pending packages to the `TO_INSTALL` array that is saved to `setupVars.conf` for later referencing when uninstalling PiVPN.
The installer now detects and offer to use Pi-hole as the DNS server for the VPN.

Add uninstall script and Pi-hole detection

---

Default.txt
auto_install/install.sh
scripts/openvpn/makeOVPN.sh
scripts/openvpn/pivpnDebug.sh
scripts/uninstall.sh
scripts/wireguard/pivpnDEBUG.sh
server_config.txt
unattended_openvpn_example.conf
unattended_wireguard_example.conf

Changes:
1) Added back unattended installation: as expected, the user can call the install script with `--unattended` followed by a config file and PiVPN will be installed non-interactively. Two examples are provided in case the user wants to customize every setting. However you don't need to specify all of them, missing one are filled with defaults IF those settings can be detected unambiguously. For example if you only have one user and one network interface the script proceeds, however if you have several of them it does not.
2) Removed `persist-key` and `persist-tun` from the client config.
3) Reverted `keepalive` setting on the server to smaller values.
See @TinCanTech's posts for the reasons of the above two: https://github.com/pivpn/pivpn/issues/864#issuecomment-553496345
4) Copied …

Unattended installation

---

auto_install/install.sh
scripts/openvpn/pivpnDebug.sh
scripts/uninstall.sh
server_config.txt

- Unquoted ${PKG_INSTALL} and ${UPDATE_PKG_CACHE} as they seem to hang the script if quoted.
- Removed [this code](https://github.com/pivpn/pivpn/compare/test...orazioedoardo:test?expand=1#diff-299d9b30c952310aace4aba77c698874L285-L294) as set -e is not used in the test branch and even if it were used, the script would exit if `debconf-apt-progress`'s exit code is NOT 100 (which is the case when no errors occur, exit code 0).
- `vpnGw="${pivpnNET/.0/.1}"` turns 10.8.0.0 into 10.8.1.0 however we need 10.8.0.1 so `vpnGw="${pivpnNET/.0.0/.0.1}"` is used.
- Create folder /var/lib/openvpn
- Removed code path related to OLD_UFW, originally used for jessie compatibility
- Other trivial changes
@corbolais what do you think?

Revert some minor changes

---

auto_install/install.sh
files/etc/openvpn/server_config.txt
scripts/openvpn/makeOVPN.sh
scripts/openvpn/removeOVPN.sh
scripts/self_check.sh
scripts/uninstall.sh
scripts/wireguard/makeCONF.sh
scripts/wireguard/removeCONF.sh

Main changes from the test branch:
1) When offering to use Pi-hole, identify VPN clients via clientname.pivpn using a dedicated hosts file. Clients can now be resolved by their names and also show up in the Pi-hole dashboard.
2) Decide whether to tell dnsmasq to listen on the VPN interface depending on the user settings. The default Pi-hole listening behavior is "Listen only on interface whatever", which means we need to add the specific VPN interface. However, if the user has  "Listen on all interfaces" or " "Listen on all interfaces, permit all origin", then we don't need to add the interface (self-explanatory).
3) Set static IPs by default when using OpenVPN, (required by 2.).
4) Restrict access to automatic backups (.tar.gz) of /etc/wireguard and /etc/openvpn to root.

Merge test into master

---

auto_install/install.sh

I think the point is clear? See https://build.openvpn.net/debian/openvpn/stable/dists/buster/main/ for supported architectures.
Adding this to non-supported systems (all ARMs) leads to apt update failures and hence breaks error handled scripts.
The alternative would be to simply remove applying this repo, which would make installs across different architectures consistent, by staying with official distro repo. But better to have a quick fix now than long discussion 😉.

Apply the x86-only OpenVPN repo on x86 systems only

---

scripts/backup.sh

This will fix #1024.
Changed:
`Backup crated to`
to:
`Backup created in`

Fix spelling & grammar in backup script

---

auto_install/install.sh
scripts/wireguard/makeCONF.sh
scripts/wireguard/removeCONF.sh

Generate a unique pre-shared key for each client as per the WireGuard protocol to improve post-quantum resistance.
1. https://www.wireguard.com/papers/wireguard.pdf#subsection.5.2
2. https://wiki.archlinux.org/index.php/WireGuard#Key_generation
3. https://doc.turris.cz/doc/en/public/wireguard

Generate unique pre-shared key for each client

---

README.md
auto_install/install.sh
scripts/openvpn/pivpnDebug.sh
scripts/pivpn
scripts/self_check.sh
scripts/uninstall.sh
scripts/wireguard/pivpnDEBUG.sh

remove refs to /etc/pivpn/setupVars in selfcheck and debug scripts
tidy indenting
on install, check if symlink already exists before making one to avoid error
uninstall indicates which vpns are available for uninstall
selfcheck checks both protocols if both present
install - additional text in reconfigure saying 2nd protocol can be added
change to use pivpn ovpn insteed of pivpn opv when dual protocols exist
change to README.md, since dual protocols not a major feature

Tidy dual VPN protocol install

---

auto_install/install.sh
scripts/openvpn/pivpn.sh
scripts/openvpn/pivpnDebug.sh
scripts/pivpn
scripts/uninstall.sh
scripts/update.sh
scripts/wireguard/pivpn.sh
scripts/wireguard/pivpnDEBUG.sh

- Allow using 'pivpn vpn -u' to directly uninstall VPN 'vpn'
- Also allow using 'pivpn -u' with two VPNs (will present a dialog).
- During uninstall, ask which VPN to remove only if there are two VPNs
- PiVPN git repo will be downloaded to '/usr/local/src/pivpn'. All scripts
in /opt/pivpn, the main pivpn script and the bash completion file,
are now just symbolic links. Resolves issue #695.
- Remove unused call to updateWireGuard().
@shelleycat485 what to you think?

Improved dual VPN uninstallation, remove duplicate code/script

---

scripts/openvpn/removeOVPN.sh
scripts/wireguard/qrcodeCONF.sh
scripts/wireguard/removeCONF.sh

As we could have many client profiles, each with complex names, I thought it would be great if we could also enter a Index value instead of the profile name for the QR code display and delete option
For example:
:: Client list ::
• [1] HomeRob
• [2] HomeRobMobile
• ....
Please enter the Index/Name of the Client to show:
Where the user can either enter '2', or 'HomeRobMobile
This PR has been tested with OpenVPN/remove and WireGuard remove/qr commands
Previous version displayed a middle-dot at the beginning of each line, but i noticed a printing issue in one of my test systems and decided to remove it.
(It looked better with the dot)
https://github.com/pivpn/pivpn/issues/1086

Feature: Add Index based option for remove/qr commands

---

scripts/openvpn/listOVPN.sh
scripts/openvpn/removeOVPN.sh

These changes allow PiVPN scripts to display and revoke certificates with common names like "José" better. Prior to this commit, names like "José" would be shown as "Jos\xC3\xA9".  In addition, certificates with names like "José" could not revoked using PiVPN scripts.
This pull request is focused on the correct branch, per [orazioedoardo](https://github.com/pivpn/pivpn/pull/1149#issuecomment-711893234)'s comment.

Handles special characters better

---

auto_install/install.sh
scripts/backup.sh
scripts/openvpn/pivpn.sh
scripts/pivpn
scripts/wireguard/pivpn.sh

When running a secondary script, the exit code of the main script will use the exit code from the secondary script instead of always returning 0.  That way errors can be detected by the exit code when using the main pivpn script.  
Also, fixed an exit code when running install.sh without sudo to return 1 instead of 0.  
This is related to Issue #1231

Fix exit codes when running a secondary script

---

auto_install/install.sh
scripts/openvpn/makeOVPN.sh
scripts/openvpn/removeOVPN.sh
scripts/wireguard/disableCONF.sh
scripts/wireguard/enableCONF.sh
scripts/wireguard/qrcodeCONF.sh
scripts/wireguard/removeCONF.sh

SC2004: "$/${} is unnecessary on arithmetic variables."
SC2006: "Use $(...) notation instead of legacy backticked `...`."
SC2129: "Consider using { cmd1; cmd2; } >> file instead of individual redirects."
SC2219: "Instead of 'let expr', prefer (( expr ))."

Fixed shellcheck warning SC2004, SC2006, SC2129, SC2219. Issue #1233.

---

auto_install/install.sh

Meanwhile the Raspberry Pi kernel package with Linux 5.10 and built-in WireGuard module has been released. It hence became effective to make use of the built-in module check on Raspbian as well to skip the overhead of kernel headers install and DKMS module build.
Additionally, when adding Bullseye repositories to make available the WireGuard packages, say so explicitly. "Adding Debian repository" / "Adding Raspbian repository" is confusing when running a Debian / Raspbian system with those repositories added already, only with an older distro release.

Skip WireGuard module build on Raspbian if it's built-in

---

auto_install/install.sh

From my comment: https://github.com/pivpn/pivpn/issues/1239#issuecomment-777427001
> By the way since Bullseye is going to ship with kernel 5.10 with built-in WireGuard, I think it makes sense to just fix the script for now to stop the installation on arm64 Debian 10.
OpenVPN should be offered to install then.

Default VPN protocols to unsupported (workaround for issue #1239)

---

auto_install/install.sh
scripts/openvpn/makeOVPN.sh

SC2015: Note that A && B || C is not if-then-else. C may run when A is true.
Replaced `[ $1 -gt 1 ] && shift $1 || shift` with `shift $1` since
`shift 1` is identical to `shift`.

Fixed shellcheck issue SC2015

---

scripts/openvpn/bash-completion
scripts/wireguard/bash-completion

SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.

Fixed shellcheck issue SC2148

---

auto_install/install.sh
scripts/wireguard/bash-completion
scripts/wireguard/clientSTAT.sh

SC2034: ___ appears unused. Verify use (or export if used externally).
I opted to remove the variables since they didn't seem to be used
anywhere.
Also wanted to test making two simultaneous pull requests to check if Github imploded.

Fixed shellcheck warning SC2034

---

auto_install/install.sh

SC2178: Variable was used as an array but is now assigned a string.
SC2128: Expanding an array without an index only gives the first element.
It's apparently a known bug that shellcheck can't both declare a
variable local and assign a value to it without raising this issue.
https://github.com/koalaman/shellcheck/wiki/SC2178

Fixed shellcheck warnings SC2178 and SC2128.

---

auto_install/install.sh

if you have a lot of ufw rules and look at them via `sudo ufw status` it would be beneficial to have comments indicating the purpose of a rule (especially with ports which are not that well-known)
e.g. on a _raspberry pi_ with _pihole_
```
% ufw status
Status: active
To                         Action      From
--                         ------      ----
51820/udp                  ALLOW       Anywhere                   # vpn
22/tcp                     ALLOW       Anywhere                   # ssh
DNS                        ALLOW       Anywhere                   # dns
80/tcp                     ALLOW       Anywhere                   # http
22/tcp (v6)                ALLOW       Anywhere (v6)              # ssh
DNS (v6)                   ALLOW       Anywhere (v6)              # dns
80/tcp …
```

ufw: add comment

---

auto_install/install.sh
examples/unattended_openvpn_example.conf
examples/unattended_wireguard_example.conf

Support setupVars for `pivpnNET`, `subnetClass` and `ALLOWED_IPS` via unattended setup.
- **OpenVPN** --> `pivpnNET` and `subnetClass`
- **Wireguard** --> `pivpnNET`, `subnetClass` and `ALLOWED_IPS`
Fix part of https://github.com/pivpn/pivpn/issues/1273

Support setupVars for pivpnNET, subnetClass and ALLOWED_IPS via unattended setup

---

scripts/openvpn/removeOVPN.sh

The action if the user does not input anything when revoking a certificate is to not revoke. Let the text reflect that by making N uppercase.

Fix typo in removeOVPN.sh for default action

---

scripts/wireguard/pivpnDEBUG.sh

Compare with `scripts/openvpn/pivpnDebug.sh`, where the escape
characters are correctly sequenced for "a tab, and then some
styled text".

Correct typo in Debug script output styling

---

scripts/wireguard/removeCONF.sh

Currently removing a client only removes the IPV4 entries from the `hosts.wireguard` file.
For IPv6, there is no need to have a NET_REDUCE since client `$COUNT` is incremented after the `::` in `$pivpnNETv6`

WireGuard: removeCONF: Remove ipv6 DNS entries too

---

auto_install/install.sh

in which case there is no dedicated file in /lib/modules. A rare case but possible.
Additionally the recursive globbing has been replaced by dpkg-query's internal recursive asterisk matching, which performs better/faster. This does now also match on "wireguard.kosomething", but I think "wireguard" is specific enough and dots in kernel modules names uncommon, to no be an issue.

Add support for builtin WireGuard module

---

auto_install/install.sh

Fixes #1556

---

auto_install/install.sh

Removed the dependency from edge repository and downloaded the `grepcidr` source code into a temp directory

Remove dependencies

---

.travis.yml
CONTRIBUTING.md
auto_install/install.sh
ciscripts/startup.sh
ciscripts/test.sh
scripts/backup.sh
scripts/openvpn/bash-completion
scripts/openvpn/clientStat.sh
scripts/openvpn/listOVPN.sh
scripts/openvpn/makeOVPN.sh
scripts/openvpn/pivpn.sh
scripts/openvpn/pivpnDebug.sh
scripts/openvpn/removeOVPN.sh
scripts/pivpn
scripts/self_check.sh
scripts/uninstall.sh
scripts/update.sh
scripts/wireguard/bash-completion
scripts/wireguard/clientSTAT.sh
scripts/wireguard/disableCONF.sh
scripts/wireguard/enableCONF.sh
scripts/wireguard/listCONF.sh
scripts/wireguard/makeCONF.sh
scripts/wireguard/pivpn.sh
scripts/wireguard/pivpnDEBUG.sh
scripts/wireguard/qrcodeCONF.sh
scripts/wireguard/removeCONF.sh

Reformatted the code

---

.releaserc
.travis.yml
auto_install/install.sh
ciscripts/pre_checks.sh
ciscripts/startup.sh
ciscripts/test.sh

Changes on this PR: 
* OS Support
* Add Support and CI tests for Ubuntu Jammy
* Removed CI tests for Ubuntu Xenial, Did not remove support for it yet. 
* Changes on CI System with the goal to streamline the testing / release process. 
* Added multiple scripts to be used bu ci testing, the goal is to keep the CI code more "DRY" and avoid too much code repetition. 
* Added the `-e` flag to the scripts so they exit if any error occurs thus failing the whole pipeline. 
* Added semantic-release, this will analyze the commits and will tag the code and create releases with Updated changes removing the need to edit the CHANGELOG.md before merging to master.
Considering That PiVPN is far from the v1.10 existing here: https://github.com/pivpn/pivpn/releases I am planning to Manually create a …

Ubuntu jammy Support and multiple updates to jammy

---

scripts/wireguard/makeCONF.sh

move file sourcing above first references to the variables it loads
userGroup var is being set using var $install_user that should be loaded from the setupVars.conf file.
the issue this brings is the chown of the configs dir (approx line 100 in makeCONF.sh) leaves that dir owned by root

fix(dev-infra): move source to before var ref

---

scripts/openvpn/clientStat.sh

At line 53 of clientStat.sh there is a printf that starts with minus sign
`  53           printf "- %s\n" "${array[9]}"
`
When **pivpn clients** command is executed the minus sign is interpreted as an option and the script fails by not printing the connection time.
I fixed the issue adding -- before the format string to disarm the minus sign.
`  53           printf -- "- %s\n" "${array[9]}"
`
Hope this helps.
Thanks
Bye.

Show correct information and fix error caused by dash on printf in clientStat.sh

---

scripts/uninstall.sh
scripts/wireguard/disableCONF.sh
scripts/wireguard/enableCONF.sh

Make user input handling look for blanks so that implied defaults work properly.
This fixes https://github.com/pivpn/pivpn/issues/1663, which is correct in that when you have a user input question and you give the options Y/n or y/N, it is implied that the capitalized letter is what the program will default to if there is no input.
Squashed copy of #1667

fix(scripts): made indicated reply defaults work correctly

---

scripts/wireguard/qrcodeCONF.sh

(supersedes #1681, submitted to the wrong branch, sorry about that).
The last couple times I've used the qr generation functionality, I make the mistake of passing the filename instead of the client name. This time it annoyed me enough to do something about it :).
Thanks for this great tool!

  fix(scripts): allow generating a QR code from a filename

---

auto_install/install.sh

On installations such as OctoPi, `git` is shadowed by `/root/bin/git`. This change forces the script to use `/usr/bin/git` which isn't affected by other executables with the name "git" in the path.

fix(core): Use absolute path for git

---

auto_install/install.sh

Add Ubuntu Lunar (Lobster) which is now available on cloud providers.
Tested with Lunar Lobster 23.04.

Update install.sh to support wider Ubuntu detection

---

auto_install/install.sh

PiVPN can now be installed and used by LXC containers.
Problem:
During the installation process, I was not able to select Wireguard for installation. It ran the OpenVPN setup automatically without a previous selection.
Fixes:
1. the `AVAILABLE_WIREGUARD` was not detected for Alpine LXC containers therefore another case has been added
2. added `libqrencode-tools` to the dependencies for Alpine installations to generate and display qrcodes
Tested the changes myself with no problems.

fix: Alpine container (LXC) wireguard support

---

scripts/wireguard/disableCONF.sh

This fix prevents "pivpn -off" from failing to disable a client when another client is already disabled and the disabled client name starts with the client name you're trying to disable. e.g. "user" wasn't able to be disabled if "user-1" was already disabled.

fix(scripts): Match full client name when disabling

---

auto_install/install.sh

For grammatical purposes, would this make sense to include wireguard in the window instead of [user] will hold your ovpn configurations. If not, feel free to close this PR as I always wondered why it wasn't added to the window to include wireguard. Thank you!

Fix: Change wording on the window

---

auto_install/install.sh
scripts/ipaddr_utils.sh
scripts/openvpn/makeOVPN.sh
scripts/openvpn/removeOVPN.sh
scripts/wireguard/makeCONF.sh
scripts/wireguard/removeCONF.sh

First off, now any subnet is allowed and when used, client IP addresses are correctly generated and do not assume /24, fixes https://github.com/pivpn/pivpn/issues/1267.
Then, the script will prevent adding more client than the subnet allows for, fixes https://github.com/pivpn/pivpn/issues/1683.
Last, edge cases in subnet generation when a user has 10.0.0.0/8 is addresses by checking another private network after 5000 iterations. Unfortunately I could not devise a way to efficiently check all empty available subnets so it's still probabilistic. In practice it work fine unless in extreme cases where there are very few holes and those are not checked.  Fixes: https://github.com/pivpn/pivpn/issues/1518.
IPv6 is taken care of by simply using the IPv4 as least significant quartets of the IPv6 …

Updates to subnet generation and client creation

---

.github/workflows/release.yaml

Hi @orazioedoardo  since you're gonna keep maintaining this, you might find this handy. 
TravisCI ended up going out of credits all the time and I got tired of having to deal with them and ended up just removed the integration from the repository. 
This action is very similar to the package we had previously for doing this and much easier to use. [go-semantic-release](https://github.com/go-semantic-release/semantic-release). 
Automated tests are not working and they may need to be rebuild with github actions if you need them. 
Ps: Rebase and merge, don't use merge commits as they don't really work well with semantic versioning / semantic-releases.

build: Add automated release actions

---

auto_install/install.sh

Adds support for detecting when a host kernel loaded wireguard. The kernel module appears loaded but the information about it may not be available.

feat(install): add support for wireguard in containers

---

auto_install/install.sh

Alpine saves iptables rules differently than Debian, and the respective services need to be enabled to persist settings across reboots. The only related issue I could find is #1773.

Fix Alpine persistence

---

scripts/wireguard/makeCONF.sh

Add the `--client-ip` option to enter any Client IP from a given range when creating a client profile for **WireGuard** VPN. This gives the user better control over which IP address will be assigned to the client.
This option is optional - if not used, the first available IP address will be chosen.
So the current functionality remains unchanged.
<details><summary>Example:</summary>
<p>
```
$ pivpn -a -h
::: Create a client conf profile
:::
::: Usage: pivpn <-a|add> [-n|--name <arg>] [-ip|--client-ip <ipv4>] [-h|--help]
:::
::: Commands:
:::  [none]               Interactive mode
:::  -n,--name            Name for the Client (default: 'rpi5')
:::  -ip,--client-ip      IPv4 address of the Client
:::  -h,--help            Show this help dialog
```
```
$ pivpn -a
Enter the Client IP from …
```

feat(scripts): add the option to enter any Client IP from a given range

---

auto_install/install.sh

UFW reports "ERROR: Invalid position at ‘1’" when attempting to insert an IPv6 rule above an IPv4 rule, which breaks IPv6 functionality on setups running UFW. This is fixed by appending the rule below all others.

Fix UFW throwing invalid position error during IPv6 configuration.

---

scripts/wireguard/makeCONF.sh

- Add a `-ip,--client-ip auto` option to enable skipping the client ip read step.
- Fix peer name default setting since  `pivpn --add --help` mentions the default is `$HOSTNAME` but that logic was not implemented.
- Minor styling fix.
Fixes #1905.

Add --client-ip/-ip 'auto' option + fix default/empty peer name logic

---

auto_install/install.sh

Since Debian Trixie, `/usr/lib/modules` is correctly considered as valid kernel module path, but 3rd party packages can formell still ship modules below `/lib/modules`, or below `/usr/lib/modules` as well on older Debian versions. Since `usrmerge`, both are effectively the same directory anyway.
Hence always consider both paths.
An alternative would be to use `modprobe wireguard &> /dev/null` only. It does not reveal whether the module is part of a package or was installed via DKMS. But even if DKMS was used, PiVPN wouldn't need to do anything different, since, obviously, DKMS is present already, and designed to automatically compile its modules on kernel upgrades.
Let me know whether I should open against `test` branch, though they are identical at time of writing.

fix(install): consider /lib and /usr/lib both as valid module paths
