- scripts/listOVPN.sh
- scripts/makeOVPN.sh
- scripts/removeOVPN.sh
Now checks if password is not blank, checks if password length is between 4 and 1024 characters, that the name doesn't contain any special characters (like spaces) and cleaned up source.  
I might add some more commits later
> Sanitization 'n input validation

- auto_install/install.sh
Checks return value of `dig`, with a fallback to `curl eth0.me`.
> Fixes #100

- auto_install/install.sh
Parenthesis fault causing failure install...
> Update install.sh for #124

- auto_install/install.sh
Fixes #133. We now check if there is a user available. If there isn't, we prompt to create a new user, ask username and password. We then create a home directory.
> Now prompts user to create new non-root user if no user is found

- auto_install/install.sh
Changed the OpenVPN repositories to the new ones, 
It will use OpenVPN stable repo and is now installing version 2.4.3
this solves issue #280 
tested the script everything worked well!
> changed to new openvpn repos

- README.md
This is mainly to mention the docker-pivpn project. I wasn't sure what to do about the Contributions section because it does contain a few of the projects in the Related Projects section, so I just left it alone.
> Added Related Projects section

- README.md
- auto_install/install.sh
Hi! 
This PR Merges to test branch changes made directly to master branch, which will make the full merge easier in the future and less prone to merging errors. 
- Added Support for Stretch
- Removed a few lines of code that appears to be useless (script worked just fine without them in all tests made). 
The following tests were made to the Test Branch reflecting already this commit:
**Debian VM 32Bit - TESTED -** Install Script OK as expected -  Not able to test VPN Connection
**Ubuntu 17.04 VM  - TESTED -** Install Script OK as expected - Not able to test VPN Connection
**Duvuan i386 VM . TESTED -** Install Script as expected - Not Able to test VPN Connection
**Duvuan x64 VM . TESTED -** Install Script as expected - Not Able to test VPN Connection
**AWS EC2 Debian 64Bit - TESTED -** …
> Stretch Support and Test Branch tests

- scripts/clientStat.sh
Code to add human readable value for `pivpn clients`
The bytes value was a little bit useless in this form.
The code check if the function `numfmt` exist into the shell context to avoid error.
Az
> Add human readable values for bytes received/sent

- auto_install/install.sh
- server_config.txt
Commented out a number of excess options that were set implicitly by using the `server` option. Source: [OpenVPN 2.4 man page (--server directive)](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage#lbAH)
> Removed excess code

- ISSUE_TEMPLATE.md
Noticed the lack of information from PiVPN users when opening issues, some of that information is quite useful to troubleshoot, so I have changed the issue template to provide us with more information than the previous one!  and added a few comments in order to to try to raise awareness for users that they need to provide us with accurate information, not just a simple "It doesn't work!"
Thanks
> Updated Issue Template

- scripts/makeOVPN.sh
Great for readable naming conventions.
> Changing name validation regex to allow dashes

- server_config.txt
> Increase keepalive to decrease phone battery usage

- auto_install/install.sh
Remove the excess code discussed in issue #552.
> Fix issue #552.

- ISSUE_TEMPLATE.md
- auto_install/install.sh
You are supposed to commit changes against the `test` branch (see CONTRIBUTING.md), so I think `test` should be updated with a rebase.
> Update test branch.

- Default.txt
- auto_install/install.sh
- scripts/makeOVPN.sh
- server_config.txt
1. The openvpn 2.4 dialog has been changed. Now if the user chooses “Yes” the installer will use ECDSA (256, 384, 521 bit with 256 being the default), ECDH (openvpn will use the curve from the certificate) and tls-crypt. Otherwise the usual RSA (1024, 2048, 4096), matching DH parameters and tls-auth.
2. Package dhcpcd5 will be installed only if the distribution is not Ubuntu Bionic (see #526). Actually i haven’t tested ubuntu 18.04 so I Ieft its status at “maybeos_support”.
3. Replaced the easy-rsa download with the official (and latest) one.
4. Simplified distro_check.
5. Linux human users start at UID 1000 so I changed the chooseuser function accordingly, otherwhise invalid users like “pihole” would show up.
6. Packages installation would fail with no visible error if the distribution …
> ECDSA support plus several fixes

- ISSUE_TEMPLATE.md
- README.md
Since changes should be made to the test branch, the test branch should be up to date.
> Update the test branch

- ISSUE_TEMPLATE.md
- README.md
- auto_install/install.sh
Adding pull request to test fork to allow for testing.
> Custom Search Domain

- auto_install/install.sh
Using a shallow clone reduces the download size.
> Use shallow clone for make_repo and update_repo.

- auto_install/install.sh
Renamed from EasyRSA-{version}.tgz to EasyRSA-unix-v{version}.tgz
> Fix Easy-RSA install

- ISSUE_TEMPLATE.md
re organized. 
also a little more strict to help with https://github.com/pivpn/pivpn/issues/723
also borrowed a few lines (3, 4, & 5) from https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md#L3
> reorganize, borrowed some words

- auto_install/install.sh
Resubmitting #729 on top of the test branch.
> Flush disk writes before reboot (resubmit)

- ISSUE_TEMPLATE.md
- README.md
- auto_install/install.sh
This PR removes the hardcoded /24 subnet while setting up DHCPCD. 
General changes to Issue template. 
General Changes to README File to better reflect the current status of PiVPN. 
@0-kaladin @redfast00 if there is anything you don't agree with please let me know so we can revert/change. 
Kind Regards.
> Removed hardcoded /24, general fixes, README Changes. 

- ISSUE_TEMPLATE.md
Issue template on master moved into test.
> Fixed issue template diff with master

- CONTRIBUTING.md
- README.md
- auto_install/install.sh
This PR adds information about getting support and incomplete issue templates.
Fixed markdown syntax error in the contributors' guide.
Related to: https://github.com/pivpn/pivpn/issues/759
> Typos and info regarding support

- auto_install/install.sh
> Add official support for Buster

- auto_install/install.sh
> Fix typo in "separated"

- scripts/makeOVPN.sh
Fixed the issues with special characters in OVPN12 files.
> Special characters in OVPN12 files

- auto_install/install.sh
Signed-off-by: corbolais <corbolais@gmail.com>
> add local resolver as DNS option.

- README.md
Added link to pivpn.dev status dashboard where everyone can see: 
Server status
response time
> Add link to pivpn.dev status dashboard

- README.md
- auto_install/install.sh
- scripts/uninstall.sh
replaced pivpn.dev with pivpn.io
> Going back to pivpn.io

- auto_install/install.sh
> Fix typo and grammar

- scripts/openvpn/listOVPN.sh
Updated listOVPN.sh script to include Expiration Dates and Cleaned up Escape Sequences.
> Updated listOVPN to Include Expiration Dates

- auto_install/install.sh
Just noticed a typo in the installer and thought I'd fix it.
> Quick typo/grammar fix

- scripts/openvpn/makeOVPN.sh
- scripts/openvpn/pivpn.sh
Looking for a way to regenerate ovpn after deletion without need for revoking and generating a new certificate for an existing client. It should fix the request https://github.com/pivpn/pivpn/issues/281.
Any suggestions for improvement are welcome.
PS: I have just started using git, I hope I am pulling the request correctly.
> Fix issue pivpn#281

- scripts/openvpn/removeOVPN.sh
- scripts/wireguard/removeCONF.sh
This PR adds a -f|--force parameter to delete a profile without a prompt (useful if you deploy it with ansible).
> add parameter to force remove profile

- scripts/openvpn/listOVPN.sh
> Showing expired certificates as such.

- auto_install/install.sh
add -D option to create the folder.
> add -D to create the folder

- auto_install/install.sh
Support was enabled automatically if a WireGuard package was found or could have been made available. But if the WireGuard kernel module is not available, it needs to be compiled. The required kernel headers are only reliably known for Raspberry Pi (Raspbian) and for amd64. This commit resolves the related issue where linux-image-amd64 was attempted to be installed on non-amd64 systems.
Additionally this commit resolves the issue that kernel headers were required and a DKMS build done, even if the module was builtin, when no WireGuard package was found.
The $NEED_WIREGUARD_REPO variable has been replaced with $AVAILABLE_WIREGUARD, which practically serves the same information and allows a simpler support check.
Fixes: #1180
_____________
Probably not the most beautiful solution, but it …
> Fix WireGuard support detection

- .github/ISSUE_TEMPLATE/bug_report.md
Last April I submitted https://github.com/pivpn/pivpn/commit/5b404ccd9c7a2cacfe27a4eb6056af17c8a88e36 and didn't proof read the issue template before I submitted the P/R so there where some grammar errors.
> use proper english in bug_report.md because i failed to proof read it last April

- auto_install/install.sh
Added -y to $UPDATE_PKG_CACHE
updatePackageCache() no longer checks if apt update was run, it will
always update package cache since its a requirement
Replaced all updates using ${UPDATE_PKG_CACHE} with
updatePackageCache()
> Fix for #1204

- scripts/wireguard/disableCONF.sh
- scripts/wireguard/enableCONF.sh
- scripts/wireguard/listCONF.sh
- scripts/wireguard/makeCONF.sh
- scripts/wireguard/pivpnDEBUG.sh
- scripts/wireguard/qrcodeCONF.sh
- scripts/wireguard/removeCONF.sh
> Fixed shellcheck warning SC2164: "Use 'cd ... || exit' or 'cd ... || ……return' in case cd fails."

- auto_install/install.sh
> Fixed shellcheck SC2155: "Declare and assign separately to avoid masking return values."

- .travis.yml
> Fixed wrong path to script in the travis file.

- scripts/openvpn/makeOVPN.sh
SC2027: The surrounding quotes actually unquote this. Remove or escape them.
> Fixed shellcheck warning SC2027

- auto_install/install.sh
Fix https://github.com/pivpn/pivpn/issues/1275. @DerDanilo
> Disable progress bar when running unattended

- auto_install/install.sh
- examples/unattended_wireguard_example.conf
- scripts/wireguard/makeCONF.sh
Adding Wireguard MTU support to fix https://github.com/pivpn/pivpn/issues/1019
> add Wireguard MTU support via setupVARS.conf

- scripts/openvpn/pivpnDebug.sh
- scripts/wireguard/pivpnDEBUG.sh
- Updated the FAQ link to point to [docs.pivpn.io](docs.pivpn.io).
- Tweaked the output header such that it doesn't show the full commit message, just the subject. After all we only need the git information to know when the user has installed PiVPN.
- Added the branch to the output.
> Debug update

- auto_install/install.sh
Raspbian images have been shipping with kernel 5.10.17 since March 4. This kernel version has the WireGuard module built in which means we don't need to check if the user has updated, neither to install the module via DKMS.
> Remove kernel version check on Raspbian

- scripts/uninstall.sh
Update "simpling" to "simply".
> Fix grammar in uninstall.sh

- auto_install/install.sh
- scripts/uninstall.sh
Fixes https://github.com/pivpn/pivpn/issues/1282
Also added a line to the uninstall script to remove the rule at uninstall time.
> Allow DNS incoming requests through UFW

- auto_install/install.sh
Satisfies feature request https://github.com/pivpn/pivpn/discussions/1424.
> Randomize wg internal subnet address

- README.md
- auto_install/install.sh
Following my comment and request (https://github.com/pivpn/pivpn/pull/1455#issuecomment-1038470635) for custom git url and branch options, here we go.
Developing and testing installation now works way easier.
> Customgitrepoandbranch

- scripts/backup.sh
- scripts/pivpn
- scripts/uninstall.sh
- scripts/wireguard/clientSTAT.sh
- scripts/wireguard/disableCONF.sh
- scripts/wireguard/enableCONF.sh
- scripts/wireguard/makeCONF.sh
- scripts/wireguard/removeCONF.sh
move err function above where it is first called
> fix(dev-infra): move function before use

- README.md
The previous headings started with a capital letter, and this one didn't. So I Fixed it!
> Made the "c" capital in Contributions, in README.md

- scripts/wireguard/makeCONF.sh
Closes https://github.com/pivpn/pivpn/issues/1790
> fix(scripts): disallow using server's name as client name

- auto_install/install.sh
In unattended install, there is no possibility to specify if user wants to use Pi-hole DNS as DNS.
Introducing a `--use-pihole` argument, user can decide if PiVPN configuration should be aligned to the Pi-hole installation.
Example of installation:
```
bash auto_install/install.sh --use-pihole
```
Example of unattended isntallation:
```
bash auto_install/install.sh --unattended pivpn.conf --use-pihole
```
If I made some mistake in the pull request procedure, code style or commit format please, forgive me :-)
> feat(install) Add possibility to use Pi-hole in unattended install
